version: "3.8"
services:
  course-db:
    image: mongo
    restart: always
    container_name: ms-course-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: courses
    volumes:
      - ms-course-db-data:/data/db
volumes:
    ms-course-db-data: