spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27017/courses?authSource=admin
      database: courses
  devtools:
    livereload:
      port: 35729
    restart:
      enabled: true
      poll-interval: 2s
      quiet-period: 1s
springdoc:
  swagger-ui:
    path: /api/courses/docs
  api-docs:
    path: /api/courses/docs
server:
  port: 8080
management:
  endpoints:
    jmx:
      exposure:
        include: 'health,info'
    web:
      base-path: '/api/courses/status'
      path-mapping:
        health: /health